site_name: tq Documentation
nav:
    - Objects: objects.md
    - Verbs: 
      - Get: get.md
      - Post: post.md
      - Put: put.md
theme: 
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true

markdown_extensions:
  - toc:
      toc_depth: 1