# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
    tags: '*'
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
      
    - name: Test
      run: go test -skip "_Integration$" -v -race -coverprofile coverage.out -covermode atomic ./...
      
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Cross compile
      run: .github/cross_compile.sh tq
      if: startsWith(github.ref, 'refs/tags/')

    - name: Bundle release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        body_path: news.md
        files: bin/*
        fail_on_unmatched_files: true
        token: ${{ secrets.REPO_TOKEN }}
